name: Pytest Marker and Parallel Runs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  smoke-tests:
    name: Smoke Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chromium (for headless Chrome)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Allure CLI
        run: |
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz
          tar -xvzf allure-2.25.0.tgz
          sudo mv allure-2.25.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest allure-pytest

      - name: Run Smoke Tests
        continue-on-error: true
        run: |
          echo "🧪 Running smoke tests..."
          pytest -m "smoke" --alluredir=reports/allure-results
        env:
          GRID_URL: ""
          PYTHONUNBUFFERED: 1

      - name: Generate Allure HTML Report
        if: always()
        run: |
          allure generate reports/allure-results -o reports/allure-html --clean

      - name: Upload Allure results (Raw XML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-smoke
          path: reports/allure-results

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-smoke
          path: reports/allure-html

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-smoke
          path: reports/screenshots/

  regression-tests:
    name: Regression Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chromium (for headless Chrome)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Allure CLI
        run: |
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz
          tar -xvzf allure-2.25.0.tgz
          sudo mv allure-2.25.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest allure-pytest

      - name: Run Regression Tests
        continue-on-error: true
        run: |
          echo "🧪 Running regression tests..."
          pytest -m "regression" --alluredir=reports/allure-results
        env:
          GRID_URL: ""
          PYTHONUNBUFFERED: 1

      - name: Generate Allure HTML Report
        if: always()
        run: |
          allure generate reports/allure-results -o reports/allure-html --clean

      - name: Upload Allure results (Raw XML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-regression
          path: reports/allure-results

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-regression
          path: reports/allure-html

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-regression
          path: reports/screenshots/

  flow-tests:
    name: Flow Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chromium (for headless Chrome)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Allure CLI
        run: |
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz
          tar -xvzf allure-2.25.0.tgz
          sudo mv allure-2.25.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest allure-pytest

      - name: Run Flow Tests
        continue-on-error: true
        run: |
          echo "🧪 Running flow tests..."
          pytest -m "flow" --alluredir=reports/allure-results
        env:
          GRID_URL: ""
          PYTHONUNBUFFERED: 1

      - name: Generate Allure HTML Report
        if: always()
        run: |
          allure generate reports/allure-results -o reports/allure-html --clean

      - name: Upload Allure results (Raw XML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-flow
          path: reports/allure-results

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-flow
          path: reports/allure-html

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-flow
          path: reports/screenshots/

  negative-tests:
    name: Negative Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chromium (for headless Chrome)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Allure CLI
        run: |
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz
          tar -xvzf allure-2.25.0.tgz
          sudo mv allure-2.25.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest allure-pytest

      - name: Run Negative Tests
        continue-on-error: true
        run: |
          echo "🧪 Running negative tests..."
          pytest -m "negative" --alluredir=reports/allure-results
        env:
          GRID_URL: ""
          PYTHONUNBUFFERED: 1

      - name: Generate Allure HTML Report
        if: always()
        run: |
          allure generate reports/allure-results -o reports/allure-html --clean

      - name: Upload Allure results (Raw XML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-negative
          path: reports/allure-results

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-negative
          path: reports/allure-html

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-negative
          path: reports/screenshots/

  parallel-tests:
    name: Parallel Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chromium (for headless Chrome)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Allure CLI
        run: |
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz
          tar -xvzf allure-2.25.0.tgz
          sudo mv allure-2.25.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest allure-pytest pytest-xdist

      - name: Run Parallel Tests
        continue-on-error: true
        run: |
          echo "🔄 Running all tests in parallel..."
          pytest -n 2 --dist=loadfile --reruns 2 --reruns-delay 3 --alluredir=reports/allure-results
        env:
          GRID_URL: ""
          PYTHONUNBUFFERED: 1
      - name: Generate Allure HTML Report
        if: always()
        run: |
          allure generate reports/allure-results -o reports/allure-html --clean

      - name: Upload Allure results (Raw XML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-parallel
          path: reports/allure-results

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-parallel
          path: reports/allure-html

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-parallel
          path: reports/screenshots/
