name: Pytest Marker and Parallel Runs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  smoke-tests:
    name: Smoke Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chromium (for headless Chrome)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Allure CLI
        run: |
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz
          tar -xvzf allure-2.25.0.tgz
          sudo mv allure-2.25.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest allure-pytest

      - name: Run Smoke Tests
        continue-on-error: true
        run: |
          echo "🧪 Running smoke tests..."
          pytest -m "smoke" --alluredir=reports/allure-results
        env:
          GRID_URL: ""
          PYTHONUNBUFFERED: 1

      - name: Generate Allure HTML Report
        if: always()
        run: |
          allure generate reports/allure-results -o reports/allure-html --clean

      - name: Upload Allure results (Raw XML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-smoke
          path: reports/allure-results

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-smoke
          path: reports/allure-html

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-smoke
          path: reports/screenshots/
