name: Pytest Marker and Parallel Runs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  marker-and-parallel-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Sequential runs per marker
          - mode: sequential
            marker: smoke
          - mode: sequential
            marker: regression
          - mode: sequential
            marker: flow
          - mode: sequential
            marker: negative
          # Parallel run for all tests
          - mode: parallel
            marker: all

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-xdist allure-pytest

      # Step 4: Run Pytest (Force Local WebDriver)
      - name: Run tests
        run: |
          echo "📝 Mode: ${{ matrix.mode }}, Marker: ${{ matrix.marker }}"
          if [ "${{ matrix.mode }}" = "parallel" ]; then
            echo "🔄 Running all tests in parallel with pytest-xdist..."
            pytest -n 2 --alluredir=reports/allure-results
          else
            echo "🧪 Running marker: ${{ matrix.marker }} sequentially..."
            pytest -m "${{ matrix.marker }}" --alluredir=reports/allure-results
          fi
        env:
          GRID_URL: ""
          PYTHONUNBUFFERED: 1

      # Step 5: Upload Allure results
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.mode }}-${{ matrix.marker }}
          path: reports/allure-results
